### ISSUE TITLE
Apache issues

### ISSUE THREAD

**Issue by NormySan** [oddhill/oddenvironment#20] opened 2017-02-02 07:39 UTC
It's not possible to restart apache with the oddenv command.

Were currently using the built in Apache server supplied by OSX. I've tried switching to using an apache installation supplied by brew and oddenv but i did not succeed in this endeavour.

Best case scenario would be if we can completely control all of our packages ourselves through brew and not rely on things supplied by the OS since they may not be running the versions we want and may cause issues between OS versions.

**Comment by AdamGerthel** [comment] 2017-12-14 16:30
Cannot reproduce the issue, closing for now. Create a new issue for moving from the build-in Apache if still needed.

**Closed as completed** 2017-12-14 16:31 UTC
